# Generated by Django 4.1.5 on 2023-01-26 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_review_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_status',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='page',
            name='moderated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagesm', to=settings.AUTH_USER_MODEL),
        ),
    ]
