# Generated by Django 4.1.5 on 2023-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='telegramID',
            field=models.IntegerField(null=True),
        ),
    ]
