# Generated by Django 4.1.5 on 2023-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_subscription_telegramid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='telegramID',
        ),
        migrations.AddField(
            model_name='user',
            name='telegramID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_verification_code',
            field=models.IntegerField(blank=True, default=0, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_verification_code_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
