# Generated by Django 4.1.5 on 2023-01-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_role_options_remove_subscription_telegramid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_verification_code',
            field=models.IntegerField(blank=True),
        ),
    ]
