# Generated by Django 4.1.5 on 2023-02-01 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_publicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='moderated_by_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
