# Generated by Django 4.1.5 on 2023-02-01 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_report_is_publicated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_publicated',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='review',
            name='published_at',
        ),
        migrations.AddField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated_by_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
