# Generated by Django 4.1.5 on 2023-02-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='added_at',
            field=models.DateTimeField(),
        ),
    ]
