# Generated by Django 4.1.5 on 2023-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_report_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checked_at',
            field=models.DateTimeField(),
        ),
    ]
