# Generated by Django 4.1.5 on 2023-01-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegramID',
            new_name='telegram_ID',
        ),
    ]
