# Generated by Django 4.1.5 on 2023-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_check_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_status',
            field=models.CharField(default=3, max_length=1),
        ),
    ]
