# Generated by Django 4.1.5 on 2023-02-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_check_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='response_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='CheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_url', models.CharField(max_length=128)),
                ('ping', models.PositiveSmallIntegerField(default=None, null=True)),
                ('response_status_code', models.CharField(max_length=3)),
                ('response_time', models.PositiveSmallIntegerField(default=None, null=True)),
                ('first_content_loading_time', models.PositiveIntegerField(default=None, null=True)),
                ('first_meaningful_content_loading_time', models.PositiveIntegerField(default=None, null=True)),
                ('largest_content_loading_time', models.PositiveIntegerField(default=None, null=True)),
                ('speed_index', models.PositiveIntegerField(default=None, null=True)),
                ('score', models.PositiveSmallIntegerField(default=None, null=True)),
                ('full_page_loading_time', models.PositiveIntegerField(default=None, null=True)),
                ('report_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('page', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.page')),
            ],
        ),
    ]
