# Generated by Django 4.1.5 on 2023-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_rename_telegram_id_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_verification_code',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_verification_code_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
