# Generated by Django 4.1.5 on 2023-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_check_response_time_checkreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkreport',
            name='report_file',
            field=models.FileField(default=None, upload_to='reports/'),
            preserve_default=False,
        ),
    ]
